org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod definition
archives_base_name=battle_showdown
mod_version=1.2.0
maven_group=com.github.saultsc
mod_id=battle_showdown

# Fabric project dependencies
fabric_loader_version=0.17.2
fabric_api_version=0.116.6+1.21.1
fabric_kotlin=1.13.6+kotlin.2.2.20

# Neoforge project dependencies
neoforge_version=21.1.182
kotlin_for_forge_version=5.10.0

# Common dependencies
minecraft_version=1.21.1
cobblemon_version=1.8.1+1.21.1
junit_version=5.1.0
junit_platform_version=1.1.0
